trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'
  


   
stages:
  - stage: build
    displayName: 'Build'
    jobs:
    - job: build
      displayName: 'Build'
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            pwd
            ls
            echo "$(System.DefaultWorkingDirectory)"
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.9'
        inputs:
          versionSpec: '$(python.version)'
      - task: PythonScript@0
        displayName: 'Install dependencies'
        inputs:
          command: 'pip install'
          workingDirectory: '${System.DefaultWorkingDirectory}'
          arguments: '-r ${System.DefaultWorkingDirectory}/requirements.txt'