trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: '$(python.version)'
    - task: PythonScript@0
      displayName: 'Install dependencies'
      inputs:
        scriptSource: 'filePath'
        scriptPath: '${BUILD_SOURCESDIRECTORY}'
        arguments: '-r ${BUILD_SOURCESDIRECTORY}/requirements.txt'
        workingDirectory: '${BUILD_SOURCESDIRECTORY}'
    - task: PythonScript@0
      displayName: 'Run function_factorial.py'
      inputs:
        command: 'python'
        workingDirectory: '${BUILD_SOURCESDIRECTORY}'
        arguments: 'function_factorial.py'
