trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'

stages:
- stage: Build
  displayName: 'Build'
 jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: BuildSolution@1
      displayName: 'Build solution'
