trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'
  


   
stages:
  - stage: build
    displayName: 'Build'
    jobs:
    - job: build

      displayName: 'Build'
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            pwd
            ls
            echo "$(System.DefaultWorkingDirectory)"
      - task: UsePythonVersion@0
      - script: python function_factorial.py
      - script: python test_function_factorial.py
