trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Execute Factorial code'
    steps:
    - script: python -m pip install -r requirements.txt
    - script: python function_factorial.py
