trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: '$(python.version)'
    - task: PythonScript@0
      displayName: 'Execute function_factorial.py'
      inputs:
        scriptSource: 'inline'
        script: python function_factorial.py
        workingDirectory: '${BUILD_SOURCESDIRECTORY}'
