trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: UsePythonVersion@0
    - task: PythonScript@0
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: 'function_factorial.py'
  