trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9'
  inputs:
    version: $(pythonVersion)

- task: Bash@3
  displayName: 'Install dependencies'
  inputs:
    command: 'bash'
    workingDirectory: 'flask_app/app'
    targetType: 'inline'
    script: |
      pip install -r requirements.txt


